---

- name: Add Host name to /etc/hosts
  blockinfile:
    marker: "<!-- {mark} {{ compose_project_name }} ANSIBLE MANAGED BLOCK -->"
    path: /etc/hosts
    block: |
      192.168.{{ network_id }}.10 {{ domain_name }}
      192.168.{{ network_id }}.11 adminer.{{ domain_name }}
      {% if solr %}
      192.168.{{ network_id }}.12 solr.{{ domain_name }}
      {% endif %}
      192.168.{{ network_id }}.13 db.{{ domain_name }}
