name: Check basic functionality

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Caching Composer dependencies for improve speed
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Get Drupal Project repository
      uses: actions/checkout@v2
      with:
        repository: 'drupal/recommended-project'
        path: './'

    - name: Run composer install
      uses: php-actions/composer@v5
      with:
        command: install --ignore-platform-reqs

    - name: Run composer update
      uses: php-actions/composer@v5
      with:
        command: update --ignore-platform-reqs

    - name: Get Drupal Dockerizer repository
      uses: actions/checkout@v2
      with:
        path: '.drupal-dockerizer'

    - name: Create basic config.yml
      run: |
        echo "---" > config.yml
        echo "" >> config.yml
        echo "compose_project_name: drupal-project" >> config.yml
        echo "user_uid: $(id -u)" >> config.yml
        echo "user_gid: $(id -g)" >> config.yml
        echo "drupal_root_dir: $GITHUB_WORKSPACE" >> config.yml

    - name: Run main playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yml
        directory: .drupal-dockerizer
        options: |
          --verbose

    - name: Run drush-commands playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: drush-commands.yml
        directory: .drupal-dockerizer
        options: |
          --verbose

    - name: Check drupal
      run: curl http://localhost | grep "Drupal"
